### ISSUE TITLE
uses VFP register arguments, 

### ISSUE THREAD

**Issue by jianghong-023** [patrickhwood/h264encoder#1]
Hi there,Please help me:
  I'am on the board sunxi H3 compile h264enconder lib appear error messages,Modify the Makefile configuration as follows 👍
   CFLAGS  = -mcpu=cortex-a8 -mfpu=vfpv4 -mfloat-abi=hard or CFLAGS  = -mcpu=cortex-a8  -mfloat-abi=softfp -mfpu=neon 
 This compilation error cannot be resolved.

H3 :
CPU
ARM Cortex-A7 Quad-Core
512KB L2-Cache (shared between four cores)
32 KB (Instruction) / 32KiB (Data) L1-Cache per core
SIMD NEON, VFP4
Virtualization
Large Physical Address Extensions (LPAE) 1TB
GPU
ARM Mali400 MP2
Featuring 1 vertex shader (GP) and 2 fragment shaders (PP).
Complies with OpenGL ES 2.0 
 
The compiler is arm-linux-gnueabihf-gcc and arm-linux-gnueabihf-g++ ,version ;
arm-linux-gnueabihf-gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

error mesaages:
 root@PisMedia:~/h264encoder# make
arm-linux-gnueabihf-gcc -g -Wall -c matroska_ebml.c -o matroska_ebml.o -mcpu=cortex-a8 -mfpu=vfpv4 -mfloat-abi=hard 
arm-linux-gnueabihf-gcc -g -Wall -c encoder.c -o encoder.o -mcpu=cortex-a8 -mfpu=vfpv4 -mfloat-abi=hard 
arm-linux-gnueabihf-gcc -g -Wall -c main.c -o main.o -mcpu=cortex-a8 -mfpu=vfpv4 -mfloat-abi=hard 
arm-linux-gnueabihf-gcc -g -Wall -c input.c -o input.o -mcpu=cortex-a8 -mfpu=vfpv4 -mfloat-abi=hard 
arm-linux-gnueabihf-gcc -g -Wall -c output.c -o output.o -mcpu=cortex-a8 -mfpu=vfpv4 -mfloat-abi=hard 
arm-linux-gnueabihf-g++ -Wall -o simpleencoder.static matroska_ebml.o encoder.o main.o input.o output.o -static -pthread -L. -lm -lrt ./linux_lib/libcedarv_osal.a ./linux_lib/libcedarxalloc.a ./linux_lib/libh264enc.a
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libcedarv_osal.a(cedarv_osal_linux.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libcedarv_osal.a(cedarv_osal_linux.o)
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libcedarxalloc.a(cdxalloc.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libcedarxalloc.a(cdxalloc.o)
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libcedarxalloc.a(allocator.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libcedarxalloc.a(allocator.o)
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libh264enc.a(H264encDrv.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libh264enc.a(H264encDrv.o)
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libh264enc.a(H264encLib.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libh264enc.a(H264encLib.o)
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libh264enc.a(H264encRateCtrl.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libh264enc.a(H264encRateCtrl.o)
/usr/bin/ld: error: simpleencoder.static uses VFP register arguments, ./linux_lib/libh264enc.a(IspDrv.o) does not
/usr/bin/ld: failed to merge target specific data of file ./linux_lib/libh264enc.a(IspDrv.o)
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'simpleencoder.static' failed
make: *** [simpleencoder.static] Error 1

**Comment by patrickhwood** [comment]
These errors are because the libraries you're linking with weren't built with the same floating point compiler settings that you're using.  You'll need to build with the proper flags and possibly a different (not gnueabihf) toolchain.

See the first answer to this question: https://stackoverflow.com/questions/9753749/arm-compilation-error-vfp-registered-used-by-executable-not-object-file
